TST,BK: add embedded case unittest for tags substitution
unfortutely not yet fully functional -- breaks on the 2nd test case since it
doesn't then look back trying to match earlier again...

$> PYTHONPATH=$PWD bin/fail2ban-testcases testSubstituteRecursiveTags
Fail2ban 0.9.1.dev test suite. Python 2.7.8 (default, Oct 18 2014, 12:50:18) [GCC 4.9.1]. Please wait...
............F
======================================================================
FAIL: testSubstituteRecursiveTags (fail2ban.tests.actiontestcase.CommandActionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/actiontestcase.py", line 78, in testSubstituteRecursiveTags
    {'A': '1.2.3.4', 'PREF': 'IPV4', 'IPV4HOST': '1.2.3.4'})
AssertionError: {'A': '<IPV4HOST>', 'PREF': 'IPV4', 'IPV4HOST': '1.2.3.4'} != {'A': '1.2.3.4', 'PREF': 'IPV4', 'IPV4HOST': '1.2.3.4'}
- {'A': '<IPV4HOST>', 'IPV4HOST': '1.2.3.4', 'PREF': 'IPV4'}
?        ^^^^ -----

+ {'A': '1.2.3.4', 'IPV4HOST': '1.2.3.4', 'PREF': 'IPV4'}
?        ^^^^^^